name: agenda_contatos
description: Um aplicativo de agenda de contatos em Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.6
  path: ^1.8.2
  mask_text_input_formatter: ^2.4.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  sqflite_common_ffi: ^2.2.5

flutter:
  uses-material-design: true